# TransProxy Basic Configuration

nacos:
  namespace: '5f1968e4-25e1-4906-a4af-b57dd3186dc5'
  log-dir: '/tmp/nacos/log'
  cache-dir: '/tmp/nacos/cache'
  ip-addr: '172.100.200.5'
  ctx-path: '/nacos'
  port: 32615
  scheme: 'http'
  data-id: 'transproxy'
  group: 'dev'
  username: 'nacos'
  password: 'nacos'
