# TransProxy Global Configuration

# system configuration
system:
  env_mode:       'dev'      # value: dev | prod
  listen_addr:    8888
  db:             'mysql'
  oss:            'local'    # value: local | ali | aws

# api接口安全性认证
auth:
  # 内部系统间调用：对称加密
  basic:
    private-key: '0YawE8IfRwHBzGQzo0cQD87B'
  # 客户端调用：jwt
  jwt:
    signing-key: 'BzTASiwuiZNg0Ltjb55ZjtA8'
    expires-time: 604800
    buffer-time: 86400

# 系统日志
log:
  director:   'log'
  level:      'info'

# redis configuration
redis:
  db: 0
  addr: '127.0.0.1:6379'
  password: ''

# db connect configuration
db:
  mysql:
    host: ''
    db-name: 'trans_proxy'
    username: 'root'
    password: 'root'
    max-idle-conns: 10
    max-open-conns: 100
    option: 'charset=utf8&parseTime=True&loc=Local'

# oss connect configuration
oss:
  local:
    path: 'uploads/file'

